project14/urls.py
from django.contrib import admin
from django.urls import path,include
from generic.views import *
import specific

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gn_overriding/',gn_overriding,name='gn_overriding'),
    path('gn_overloading/',gn_overloading,name='gn_overloading'),
    path('specific/',include('specific.urls')),
]

specific/urls.py
from specific.views import *
from django.urls import path
app_name='itr'

urlpatterns=[
    path('sp_iterator/',sp_iterator,name='sp_iterator'),
    path('sp_generator/',sp_generator,name='sp_generator'),
]

generic/models.py
from django.db import models

# Create your models here.

specific/models.py
from django.db import models

# Create your models here.

generic/views.py
from django.shortcuts import render

# Create your views here.
def gn_overriding(request):
    return render(request,'gn_overriding.html')

def gn_overloading(request):
    return render(request, 'gn_overloading.html')

specific/views.py
from django.shortcuts import render

# Create your views here.
def sp_iterator(request):
    return render(request,'sp_iterator.html')

def sp_generator(request):
    return render(request,'sp_generator.html')

templates/gn_overloading.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>sp_overloading</title>
</head>
<body>
    <h1>Method Overloading:-</h1>
    <center>
        <h2>In overloading we need to declare multiple methods with same name
            and different method signature,we can't perform method overloading
            in python.
        </h2>
        <a href="{% url 'gn_overriding' %}"><h3>Know about overriding...</h3></a>
        <a href="{% url 'itr:sp_generator' %}"><h3>Know about generator...</h3></a>
        <a href="{% url 'itr:sp_iterator' %}"><h3>Know about iterator...</h3></a>
    </center>
</body>
</html>

templates/gn_overriding.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>overriding</title>
</head>
<body>
    <h1>Method Overriding:-</h1>
    <center>
        <h2>To perform method overriding inheritance is must require,We declare 
            methods with same name and same method signature in parent class as
            well as child class,then parent method overriden with child method.
        </h2>
       <a href="{% url 'gn_overloading' %}"><h3>Know about overloading...</h3></a>
       <a href="{% url 'itr:sp_generator' %}"><h3>Know about generator...</h3></a>
       <a href="{% url 'itr:sp_iterator' %}"><h3>Know about iterator...</h3></a>
    </center>
</body>
</html>

templates/sp_generator.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>generator</title>
</head>
<body>
    <h1>Generator:-</h1>
    <center>
        <h2>Generator is creating using generator expression and generator function.</h2>
        <a href="{% url 'itr:sp_iterator' %}"><h3>Know about iterator...</h3></a>
        <a href="{% url 'gn_overriding' %}"><h3>Know about overriding...</h3></a>
        <a href="{% url 'gn_overloading' %}"><h3>Know about overloading...</h3></a>
    </center>
</body>
</html>

templates/sp_iterator.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>iterator</title>
</head>
<body>
    <h1>Iterator:-</h1>
    <center>
        <h2>
            Iterator is an object that is created with the help of iter() with the help of iterable.
        </h2>
        <a href="{% url 'itr:sp_generator' %}"><h3>Know about generator...</h3></a>
        <a href="{% url 'gn_overriding' %}"><h3>Know about overriding...</h3></a>
        <a href="{% url 'gn_overloading' %}"><h3>Know about overloading...</h3></a>
    </center>
</body>
</html>